x-veld:
  code:
    about:
      description: ""
      topics:
        - "NLP"
        - "Machine learning"
        - "tokenization"
        - "lemmatization"
        - "part of speech"
        - "dependency parsing"
        - "universal dependencies"
        - "grammatical annotation"

    inputs:
      volume: "/veld/input/"
      file_formats: "conllu"
      contents:
        - "tokenized text"
        - "lemmatized text"
        - "part of speech of text"
        - "universal dependencies of text"
        - "grammatically annotated text"
        - "linguistic data"
        - "NLP data"

    outputs:
      volume: "/veld/outputs/"
      file_formats: "json"
      contents: 
        - "statistics"
        - "NLP data"

services:
  veld:
    build: .
    command: jupyter notebook --allow-root --ip='*' --NotebookApp.token='' --NotebookApp.password=''
    ports:
      - 8888:8888
    working_dir: /veld/code/
    volumes:
      - ./src:/veld/code/

