x-veld:
  code:
    about:
      description: ""
      topics: ""

    inputs:
      volume: ""
      file_formats: ""
      contents: ""

    outputs:
      volume: ""
      file_formats: ""
      contents: ""

    environment:
      template_var:
        description: ""
        type: ""
        optional: ""
        default: ""

services:
  veld:
    build: .
    command: jupyter notebook --allow-root --ip='*' --NotebookApp.token='' --NotebookApp.password=''
    ports:
      - 8888:8888
    working_dir: /veld/code/
    volumes:
      - ./src:/veld/code/
    environment:
      template_var: ""

